### PR TITLE
Support for custom icons in PersistentSearch, new documentation

### PR DESCRIPTION
**Pull request by michaldivis**
... I've added documentation for Persistent Search and Autocomplete.

### CODE REVIEW

**Comment by michaldivis** [comment]
I've also added support for custom `PersistentSearch` icons and updated the docs to show that functionality.

**Comment by michaldivis** [comment]
Added documentation for TextBoxSuggestions and BusyOverlay

**Comment by michaldivis** [comment]
@spiegelp ?

**Comment by spiegelp** [comment]
@michaldivis I saw the PR but didn't have much freetime during the last weeks. I will look at it these days.

**Comment by michaldivis** [comment]
@spiegelp thank you!

**Comment by spiegelp** [comment]
@michaldivis thank you

**Pull request merged**
